### ISSUE TITLE
add  icon images.

### ISSUE THREAD

**Issue by zhoujin7** [rlv-dan/Snap2HTML#1]
add  icon images.

**Comment by Stamimail** [comment]
+1
Is there really a way to generate icons as the local PC icons?
I guess you can't generate all the various exe icons (just the default one),
but you can generate the images of the common icons as pdf,mp3,mp4 etc...

**Comment by Emmaloto** [comment]
Hey @rlv-dan I plan on looking into this one and making a PR, unless you think otherwise.
