### ISSUE TITLE
Is there a way to automatically open all TOP level folders?

### ISSUE THREAD

**Issue by Surrylic** [rlv-dan/Snap2HTML#10]
I admit I know absolutely nothing about js or html or any kind of coding, so I apologize if it's obvious or impossible. Just curious if we can have the highest level of the folder structure already expanded upon launch of the page, while leaving all the others collapsed. Thank you!

Steve

**Comment by rlv-dan** [comment]
Yes, that would be possible by editing the html template. I do not plan on making this into a configuration.
