### ISSUE TITLE
suggestion: Export entire dir structure

### ISSUE THREAD

**Issue by elig0n** [rlv-dan/Snap2HTML#12]
currently I only see option to export **view** which means current subdirectory but it would be really cool if it was possible to export entire directory structure as json/plain/etc....

**Comment by rlv-dan** [comment]
Search for * to get everything!

**Comment by danieltroger** [comment]
**This should be at the top of the README in fat letters.**

However, searching for * on >400k files makes my browser to stop responding.

**Comment by danieltroger** [comment]
The tab's still not responding

**Comment by danieltroger** [comment]
The tab is still not responding, after 22 minutes. This is not a viable option, you need to add a better export feature.

**Comment by danieltroger** [comment]
BTW I'm using firefox developer edition with the per thread RAM limit set to 8GB on an i7-8700K overclocked to 5GHz on all 6 cores and I have 48GB RAM. So don't come with yOuR cOmPuTeR jUsT sUcKs.

Also the tab is currently sucking 7.76GB, so it will crash soon

**Comment by danieltroger** [comment]
Just chiming in to say it weirdly enough didn't crash yet. It's still running on 99% CPU, after 2 hours, and has now allocated 8.27GB RAM. But I think you get the point, it's not feasible

**Comment by rlv-dan** [comment]
@danieltroger please make sure you are using the latest version (2.14) in which I addressed this problem.
