### ISSUE TITLE
Processing folders with a lot of content.

### ISSUE THREAD

**Issue by Wulluby** [rlv-dan/Snap2HTML#14]
Hi, love this tool. I was running this last night and noticed that while it processed smaller test folders with no difficulty it wasn't writing output for larger folders, size on disk didn't seem to matter, I think it might have been number of files contained. Is this something you guys have observed elsewhere?

I ran against my C:\Temp which is 2.12GB and contains 438 files, 179 folders. It looked like it worked through the contents in a good time but then sat overnight with a message at the bottom of the GUI, "Processing Content", no output was written.

This was ran on  Windows 10, 1803.

**Comment by rlv-dan** [comment]
[snap2html debug.zip](https://github.com/rlv-dan/Snap2HTML/files/4422158/snap2html.debug.zip)

Hello. I am not able to recreate this bug at home. Please help me!

Attached is a copy of snap2html that I built to debug your problem. It will create an xml file in the same place as the html file would be saved. This is done before the problem you describe occurs and the program hangs. Please use it, and send the xml file (zipped) to me so I can examine it.

**Comment by Wulluby** [comment]
Hi Dan and thanks for the email.

I was using this on a work computer, Will have a look again on Monday if that’s ok? I suspect it might be tricky for me to get the xml output of the computer without triggering infosec’s potential data exfiltration flags. Will have a look. I’m wondering if it’s our McAfee av.


Sent from my phone.

On 2 Apr 2020, at 17:07, Dan <notifications@github.com> wrote:

﻿

snap2html debug.zip<https://github.com/rlv-dan/Snap2HTML/files/4422158/snap2html.debug.zip>

Hello. I am not able to recreate this bug at home. Please help me!

Attached is a copy of snap2html that I built to debug your problem. It will create an xml file in the same place as the html file would be saved. This is done before the problem you describe occurs and the program hangs. Please use it, and send the xml file (zipped) to me so I can examine it.

**Comment by Zig75** [comment]
Hello, as Wulluby said, love your tool too ! But unfortunately, I'm encountering the exact same issue trying to index a huge hard drive. I'll try to run the debug version you send and let you know the result.

Many thanks,
/Z

**Comment by Zig75** [comment]
Hello RLV-Dan, as promised please find attached the XML file generated with the debug app. The workstation used is running with Win 10 and the HDD to process is a large 18TB disk attached through USB3.
[Archive.html.xml.zip](https://github.com/rlv-dan/Snap2HTML/files/4480929/Archive.html.xml.zip)
Once again, many thanks for your help,

**Comment by rlv-dan** [comment]
Hello @Wulluby and @Zig75. The debug version posted above did not work as I had hoped. But I finally found a computer where I was able to reproduce the issue. Appears to have been threading problem. Attached is an updated version where I have worked to fix these problems. Please help me verify that it works now!

[Snap2HTML 2.11.zip](https://github.com/rlv-dan/Snap2HTML/files/4488715/Snap2HTML.2.11.zip)

**Comment by Zig75** [comment]
Hello Dan,
I've just tested the updated version you had the kindness to provide us and on my side, this one perfectly solve the issue, the final HTML file is correctly generated and it no longer end up with the "Processing Content" sticking message!
I would like to warmly thank you for your support and reactivity, it's very much appreciated and also once again for this super useful tool ! Many thanks !!!
Best,
/Z

**Comment by Wulluby** [comment]
Yeah that works well for me now too, thanks.
