### ISSUE TITLE
is there any way to compile this to Mac?

### ISSUE THREAD

**Issue by emilianos** [rlv-dan/Snap2HTML#17]

**Comment by rlv-dan** [comment]
It might be possible to run on Wine. But I have no Mac so I can't test.

The GUI is built on WinForms, so it will not compile on Mac. But the actual code that collect files and generates the html is separate and generic. It would probably be possible to extract and port to .Net Core as a command line tool!

**Comment by homeisfar** [comment]
@emilianos I was wondering a similar thing, and found a project called DiogenesList which is a Python implementation using Snap2HTML's template to operate on Linux. It's very buggy so I improved it. I haven't tested my version on a Mac, but I don't see why it shouldn't work, provided you're comfortable with using it in a terminal (no plans to implement a GUI).

https://github.com/homeisfar/LinuxDir2HTML

Big thanks to Dan for the original tool, which helped me organize my personal files while on Windows.

**Comment by emilianos** [comment]
thanks @homeisfar, ill give it a try!
I think I ended up using tree on the terminal like described here: https://rschu.me/list-a-directory-with-tree-command-on-mac-os-x-3b2d4c4a4827
