### ISSUE TITLE
Add an option to load a file list from a text file

### ISSUE THREAD

**Issue by Stamimail** [rlv-dan/Snap2HTML#19]
In a case the user has a file list in txt file like this:

"C:\Snap2HTML\Snap2HTML"
"C:\Snap2HTML\Snap2HTML\ReadMe.txt"
"C:\Snap2HTML\Snap2HTML\Snap2HTML.exe"
"C:\Snap2HTML\Snap2HTML\template.html"

or like this:

C:\Snap2HTML\Snap2HTML
C:\Snap2HTML\Snap2HTML\ReadMe.txt
C:\Snap2HTML\Snap2HTML\Snap2HTML.exe
C:\Snap2HTML\Snap2HTML\template.html

and he wants to view the file list in Explorer view

**Comment by rlv-dan** [comment]
I am planning to do a CSV import eventually. This would cover your use case.

**Comment by Chaphasilor** [comment]
Any news on that CSV import? :)

**Comment by Chaphasilor** [comment]
@rlv-dan

**Comment by Stamimail** [comment]
Still waiting for the import feature
https://www.voidtools.com/forum/viewtopic.php?f=10&t=10875

**Comment by Stamimail** [comment]
Also support for TXT filelist:

while
C:\Snap2HTML\Snap2HTML
is considered as a file
and
C:\Snap2HTML\Snap2HTML\
is considered as a folder.
