### ISSUE TITLE
Any plans for Linux?

### ISSUE THREAD

**Issue by mohammad-soozande** [rlv-dan/Snap2HTML#2]
This tool is great!
Do you have any plans on making it for linux?

**Comment by rlv-dan** [comment]
I'm not a Linux user, so I don't have the knowledge to do it. Snap2HTML is written in C#/WinForms so it could potentially run already under Wine?

**Comment by mohammad-soozande** [comment]
It works with wine, but it crashes time to time.

**Comment by mohammad-soozande** [comment]
Thanks anyway🙌
