### ISSUE TITLE
Bug with Network Storage

### ISSUE THREAD

**Issue by Stamimail** [rlv-dan/Snap2HTML#21]
It counts folders and files, but in result shows only files.

**Comment by rlv-dan** [comment]
Can you please explain in more detail what you are doing? Screenshots are welcome.

**Comment by Stamimail** [comment]
I'm saying that, when I used Snap2HTML on a local storage it was OK.
But when I tried to use Snap2HTML on a network storage (\\Shared\folder):
It counts folders and files (in program processing), but in result (in web-browser) shows only the files of the root folder.
All subfolders and their contents do not appear like expected.

**Comment by rlv-dan** [comment]
Solved in 2.14
