### ISSUE TITLE
The Folder column

### ISSUE THREAD

**Issue by Julien-asv** [rlv-dan/Snap2HTML#27]
Hi,
I have discovered Snap2HTML last week-end and it's a really great app, i really enjoy it.
But something bug me quickly.
If i scan a folder with files and subfolders, i generate a HTML. I make a search of a file, and i don't anderstand why, sometimes i have a column "Folder" where is the path of the file i am looking for is, and for somes HTML generated i don't have that column.
I run some quick test and it's look like i have the column with less files/folders scan.
This column is really helpfull and i wouldlike have it in all HTML generated.
Is that possible ?

Thank you

**Comment by rlv-dan** [comment]
Hello. This is not a bug, but I understand the confusion. Story time: In older versions there was some major performance problems when using the search function if you had a lot of files. Basically the app would freeze. I was unable to solve it despite spending a great deal of hours on it. It seemed to have something to do with the table though. I could see that removing the "Folder" column helped a lot. Can't explain why. But it is not acceptable that the app freezes, so I had to do something. So I put a limit of 5000 items. If more than that, the Folder column will not show. It is possible to change this value by altering the template.html file. Sorry for the confusion.
