### ISSUE TITLE
Update "open folder selection dialog box"

### ISSUE THREAD

**Issue by Sopor** [rlv-dan/Snap2HTML#28]
The "open folder selection dialog box" you use is a bit old. Maybe you could update to the new one?

![image](https://user-images.githubusercontent.com/5789283/109073205-5da41980-76f6-11eb-9235-75fd9153db08.png)

**Comment by rlv-dan** [comment]
In my opinion, the classic dialog is more distinct since it is so different from the *file* dialog. The only benefit I know is the ability to choose multiple folders, but that is not relevant for snap2html at the moment.

**Comment by Sopor** [comment]
It is also much easier to paste in a path i have in the clipboard instead of browse all the way.

**Comment by rlv-dan** [comment]
I have plans to add support for multiple root folders in Snap2html. When I do, this dialog will become more relevant to use.
