### ISSUE TITLE
Use relative paths instead of absolute path

### ISSUE THREAD

**Issue by msalaht** [rlv-dan/Snap2HTML#3]
I wish you can alter the template.html to use virtual path instead of the real path, so if I used an indexed html file on a cdrom to display it's contents it would work anywhere despite the drives letter.

**Comment by rlv-dan** [comment]
This should be possible already. Check the readme file to see different ways to link files. I know it can be tricky, but experiment and I'm sure you will get it to work!

**Comment by msalaht** [comment]
Will investigate it more, thank you 👍
