### ISSUE TITLE
Display the relative or absolute path to the file in the file information field

### ISSUE THREAD

**Issue by cxplay** [rlv-dan/Snap2HTML#34]
In some cases it is sufficient to know the path to a file, but neither the direct file information nor the search file information will show the path to the file.
Without linking these files to a network or local address, the search results are often confusing, and even if the file is found, there is no way to know where it is located.

**Comment by mantered** [comment]
If you have more than 5k files the path column is not shown when searching. You can use a text editor to search the html file for:
"if( numberOfFiles > 5000 )" and increase the limit. I'm not sure why is that limit there, I've tested with 600k files and it was working fine.

**Comment by cxplay** [comment]
> If you have more than 5k files the path column is not shown when searching. You can use a text editor to search the html file for: "if( numberOfFiles > 5000 )" and increase the limit. I'm not sure why is that limit there, I've tested with 600k files and it was working fine. Later edit: It was explained why in a closed issue ...

OK, thanks, I will be try.😉
