### ISSUE TITLE
Suppress path in url

### ISSUE THREAD

**Issue by bascurtiz** [rlv-dan/Snap2HTML#48]
Is there a way to suppress path in url?

![image](https://github.com/rlv-dan/Snap2HTML/assets/34075088/7cbb877d-5666-4866-be54-b1ccc0a8187f)

It's no biggie, but I'd like to keep it clean, so that the part after # is simply not showing.

**Comment by rlv-dan** [comment]
Edit `template.html` and remove this line:

`location.hash = '#' + currentDir;`
