### ISSUE TITLE
date format in 2.14

### ISSUE THREAD

**Issue by mtabdar** [rlv-dan/Snap2HTML#50]
i was using version 2.0 for a long time then i noticed version 2.14 is released so i changed to the new version. but since i am using my costume template, dates are not formatted. it seems that i have to change something in my template but don't know what and where!
i appreciate if anyone could help.

**Comment by rlv-dan** [comment]
Search for the following snippet in `template.html`:

```
function timestampToDate(timestamp){
	// Convert UNIX timestamp to local date
	// If you don't like the date format, try something else, such as toLocaleDateString() manually formatting the date here
	return new Date(timestamp * 1000).toLocaleString();
}
```
