### ISSUE TITLE
Error when using paths or title containing a comma character ","

### ISSUE THREAD

**Issue by omareg94** [rlv-dan/Snap2HTML#6]
When I use argument values that contain the comma "`,`" character I get unhandled exception error.

Examples of commands that generates error:
`Snap2HTML -path:"C:\folder\to\snap\path\containing, comma\" -outfile:"c:\file\output\path\file name containing, comma.html" -link:"C:\folder\to\link\to\path\containing, comma\" -title:"Title, containing, comma"`

If any of the arguments contains a comma `,`, the application generates unhandled exception error.

**Comment by rlv-dan** [comment]
Thank you. Will have a look at this in the next version!

**Comment by rlv-dan** [comment]
Fixed in 2.1
