### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Chaython** [rlv-dan/Snap2HTML#8]
In the root dir, there's no option to paste a dir, why not? 
In Export I see no option to export except to copy the text and create a file.
Thanks for this tool, works for my needs, too bad you abandoned it, 2 years ago.

**Comment by rlv-dan** [comment]
Your suggestions have been noted. Snap2HTML is not abandoned. But I don't have all the time in the world you know...

**Comment by Chaython** [comment]
Sorry, I don't know, I just found this project yesterday. Normally if something isn't abandoned there was at least 1 change in the past 9 months 😋
Thanks
________________________________

**Comment by rlv-dan** [comment]
Save export as file is added in 2.1

**Comment by NikeAddida** [comment]
Hello, is there any way to make the result's background dark?
Like a dark theme for Snap2HTML.
