### ISSUE TITLE
[BUG]  date modified sorting

### ISSUE THREAD

**Issue by kidzgy** [rlv-dan/Snap2HTML#9]
http://tva1.sinaimg.cn/large/007X8olVly1g6prhkl5egj30bv0390sk.jpg
The following text was generated by Google Translate:
As shown in the figure, the revision dates are arranged in reverse order, and 2018/10/19 should be ranked ahead of 2018/8/15, but not. I think it should be date sorting in the form of text, not in the form of dates.

**Comment by rlv-dan** [comment]
Fixed in 2.1
